// PomiABSPro - Exercise Database (100 Office Workouts)

export interface Exercise {
  id: string;
  name: string;
  nameEs: string;
  category: 'chair' | 'strength' | 'cardio' | 'office' | 'stretch' | 'yoga';
  muscles: string[];
  reps: number;
  sets: number;
  restSeconds: number;
  requiresFloor: boolean;
  requiresJumps: boolean;
  requiresEquipment: boolean;
  difficulty: 1 | 2 | 3;
  instructions: string;
  instructionsEs: string;
}

export const exercises: Exercise[] = [
  // CHAIR EXERCISES
  {
    id: 'chair-jack',
    name: 'Chair Jack',
    nameEs: 'Jack en Silla',
    category: 'chair',
    muscles: ['core', 'legs'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit upright. Spread legs and arms wide, then bring back together.',
    instructionsEs: 'Siéntate erguido. Abre piernas y brazos, luego cierra.',
  },
  {
    id: 'cycling-crunches',
    name: 'Cycling Crunches',
    nameEs: 'Abdominales Bicicleta',
    category: 'chair',
    muscles: ['core', 'obliques'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Lean back slightly. Alternate bringing knee to opposite elbow.',
    instructionsEs: 'Inclínate hacia atrás. Alterna rodilla al codo opuesto.',
  },
  {
    id: 'knee-elbow-twists',
    name: 'Knee-to-Elbow Twists',
    nameEs: 'Giros Rodilla-Codo',
    category: 'chair',
    muscles: ['core', 'obliques'],
    reps: 16,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Twist torso bringing right elbow to left knee, alternate.',
    instructionsEs: 'Gira el torso llevando codo derecho a rodilla izquierda, alterna.',
  },
  {
    id: 'leg-raises-twist',
    name: 'Leg Raises with Twist',
    nameEs: 'Elevaciones con Giro',
    category: 'chair',
    muscles: ['core', 'hip-flexors'],
    reps: 12,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Raise both legs, twist to one side, lower. Repeat other side.',
    instructionsEs: 'Eleva ambas piernas, gira a un lado, baja. Repite al otro lado.',
  },
  {
    id: 'chair-leg-raises',
    name: 'Chair Leg Raises',
    nameEs: 'Elevaciones de Pierna',
    category: 'chair',
    muscles: ['core', 'quads'],
    reps: 15,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit upright. Extend legs straight out, hold, lower slowly.',
    instructionsEs: 'Siéntate erguido. Extiende piernas rectas, mantén, baja lento.',
  },
  {
    id: 'tricep-dips-chair',
    name: 'Tricep Dips',
    nameEs: 'Fondos de Tríceps',
    category: 'strength',
    muscles: ['triceps', 'shoulders'],
    reps: 12,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on chair edge. Lower body by bending elbows, push back up.',
    instructionsEs: 'Manos en el borde. Baja doblando codos, empuja hacia arriba.',
  },
  // STRENGTH
  {
    id: 'wall-pushups',
    name: 'Wall Push-ups',
    nameEs: 'Lagartijas de Pared',
    category: 'strength',
    muscles: ['chest', 'triceps', 'shoulders'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Face wall, arms extended. Lower chest to wall, push back.',
    instructionsEs: 'Frente a la pared, brazos extendidos. Baja el pecho, empuja.',
  },
  {
    id: 'chair-squats',
    name: 'Chair Squats',
    nameEs: 'Sentadillas con Silla',
    category: 'strength',
    muscles: ['quads', 'glutes'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Stand in front of chair. Squat until touching seat, stand up.',
    instructionsEs: 'De pie frente a la silla. Baja hasta tocar, levántate.',
  },
  {
    id: 'calf-raises',
    name: 'Calf Raises',
    nameEs: 'Elevaciones de Pantorrilla',
    category: 'strength',
    muscles: ['calves'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Stand tall. Rise onto toes, hold, lower slowly.',
    instructionsEs: 'De pie erguido. Sube a las puntas, mantén, baja lento.',
  },
  {
    id: 'wide-squats',
    name: 'Wide Squats',
    nameEs: 'Sentadilla Sumo',
    category: 'strength',
    muscles: ['quads', 'glutes', 'inner-thighs'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Wide stance, toes out. Squat deep, keep back straight.',
    instructionsEs: 'Postura amplia, puntas afuera. Baja profundo, espalda recta.',
  },
  // CARDIO
  {
    id: 'high-knees',
    name: 'High Knees',
    nameEs: 'Rodillas Altas',
    category: 'cardio',
    muscles: ['core', 'quads', 'cardio'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Run in place bringing knees high. Fast pace.',
    instructionsEs: 'Corre en tu lugar elevando rodillas. Ritmo rápido.',
  },
  {
    id: 'march-steps',
    name: 'March Steps',
    nameEs: 'Marcha en Lugar',
    category: 'cardio',
    muscles: ['core', 'legs', 'cardio'],
    reps: 40,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'March in place with high knees. Control your breathing.',
    instructionsEs: 'Marcha en lugar con rodillas altas. Controla la respiración.',
  },
  {
    id: 'punches',
    name: 'Standing Punches',
    nameEs: 'Golpes de Pie',
    category: 'cardio',
    muscles: ['shoulders', 'core', 'cardio'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Athletic stance. Alternate jab and cross punches.',
    instructionsEs: 'Postura atlética. Alterna jab y cross.',
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    nameEs: 'Saltos de Tijera',
    category: 'cardio',
    muscles: ['full-body', 'cardio'],
    reps: 25,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Jump spreading legs and raising arms, return to start.',
    instructionsEs: 'Salta abriendo piernas y brazos, vuelve al inicio.',
  },
  // OFFICE SPECIFIC
  {
    id: 'desk-plank',
    name: 'Desk Plank',
    nameEs: 'Plancha de Escritorio',
    category: 'office',
    muscles: ['core', 'shoulders'],
    reps: 1,
    sets: 3,
    restSeconds: 60,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on desk edge. Hold plank position for 30-60 seconds.',
    instructionsEs: 'Manos en el borde del escritorio. Mantén plancha 30-60 seg.',
  },
  {
    id: 'seated-boxer',
    name: 'Seated Boxer',
    nameEs: 'Boxeador Sentado',
    category: 'office',
    muscles: ['shoulders', 'core'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit tall. Throw alternating punches with rotation.',
    instructionsEs: 'Siéntate erguido. Lanza golpes alternados con rotación.',
  },
  {
    id: 'arm-circles',
    name: 'Arm Circles',
    nameEs: 'Círculos de Brazos',
    category: 'office',
    muscles: ['shoulders'],
    reps: 20,
    sets: 3,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Arms extended. Make small circles forward, then backward.',
    instructionsEs: 'Brazos extendidos. Haz círculos pequeños adelante, luego atrás.',
  },
  // STRETCHES
  {
    id: 'neck-rolls',
    name: 'Neck Rolls',
    nameEs: 'Giros de Cuello',
    category: 'stretch',
    muscles: ['neck'],
    reps: 10,
    sets: 2,
    restSeconds: 15,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Slowly roll head in circles. 5 each direction.',
    instructionsEs: 'Gira la cabeza lentamente en círculos. 5 cada dirección.',
  },
  {
    id: 'shoulder-stretch',
    name: 'Shoulder Stretch',
    nameEs: 'Estiramiento de Hombro',
    category: 'stretch',
    muscles: ['shoulders'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Cross arm over chest. Hold 20-30 seconds each side.',
    instructionsEs: 'Cruza el brazo sobre el pecho. Mantén 20-30 seg cada lado.',
  },
  {
    id: 'wrist-stretch',
    name: 'Wrist Stretch',
    nameEs: 'Estiramiento de Muñeca',
    category: 'stretch',
    muscles: ['wrists', 'forearms'],
    reps: 1,
    sets: 3,
    restSeconds: 15,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Extend arm, pull fingers back gently. Hold 15 sec each.',
    instructionsEs: 'Extiende el brazo, jala los dedos suavemente. 15 seg cada uno.',
  },
  {
    id: 'seated-twist',
    name: 'Seated Twist',
    nameEs: 'Giro Sentado',
    category: 'stretch',
    muscles: ['back', 'obliques'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit tall. Twist to one side, hold. Repeat other side.',
    instructionsEs: 'Siéntate erguido. Gira a un lado, mantén. Repite al otro.',
  },
  // YOGA
  {
    id: 'chair-tree-pose',
    name: 'Chair Tree Pose',
    nameEs: 'Postura del Árbol',
    category: 'yoga',
    muscles: ['balance', 'legs', 'core'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Stand on one leg, foot on ankle or calf. Arms up. Hold 30 sec.',
    instructionsEs: 'De pie en una pierna, pie en tobillo o pantorrilla. Brazos arriba. 30 seg.',
  },
  {
    id: 'chair-warrior',
    name: 'Chair Warrior I',
    nameEs: 'Guerrero I en Silla',
    category: 'yoga',
    muscles: ['legs', 'hips', 'shoulders'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'One leg forward, back leg extended. Arms overhead. Hold 30 sec.',
    instructionsEs: 'Una pierna adelante, la otra atrás. Brazos arriba. Mantén 30 seg.',
  },
  {
    id: 'cat-cow-seated',
    name: 'Seated Cat-Cow',
    nameEs: 'Gato-Vaca Sentado',
    category: 'yoga',
    muscles: ['spine', 'core'],
    reps: 10,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Arch back looking up (cow), round back chin to chest (cat).',
    instructionsEs: 'Arquea la espalda mirando arriba (vaca), redondea barbilla al pecho (gato).',
  },
];

export const getExercisesByCategory = (category: Exercise['category']) => 
  exercises.filter(e => e.category === category);

export const getFilteredExercises = (
  noJumps: boolean,
  noFloor: boolean,
  noEquipment: boolean
) => exercises.filter(e => 
  (!noJumps || !e.requiresJumps) &&
  (!noFloor || !e.requiresFloor) &&
  (!noEquipment || !e.requiresEquipment)
);
