// Cardio exercises for office environments
import { Exercise } from '../exercises';

export const cardioExercises: Exercise[] = [
  {
    id: 'high-knees',
    name: 'High Knees',
    nameEs: 'Rodillas Altas',
    category: 'cardio',
    muscles: ['core', 'quads', 'cardio'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Run in place bringing knees high. Fast pace.',
    instructionsEs: 'Corre en tu lugar elevando rodillas. Ritmo rápido.',
  },
  {
    id: 'march-steps',
    name: 'March Steps',
    nameEs: 'Marcha en Lugar',
    category: 'cardio',
    muscles: ['core', 'legs', 'cardio'],
    reps: 40,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'March in place with high knees. Control your breathing.',
    instructionsEs: 'Marcha en lugar con rodillas altas. Controla la respiración.',
  },
  {
    id: 'punches',
    name: 'Standing Punches',
    nameEs: 'Golpes de Pie',
    category: 'cardio',
    muscles: ['shoulders', 'core', 'cardio'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Athletic stance. Alternate jab and cross punches.',
    instructionsEs: 'Postura atlética. Alterna jab y cross.',
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    nameEs: 'Saltos de Tijera',
    category: 'cardio',
    muscles: ['full-body', 'cardio'],
    reps: 25,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Jump spreading legs and raising arms, return to start.',
    instructionsEs: 'Salta abriendo piernas y brazos, vuelve al inicio.',
  },
  {
    id: 'step-touch',
    name: 'Step Touch',
    nameEs: 'Paso Toque',
    category: 'cardio',
    muscles: ['legs', 'cardio'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Step to the side, touch other foot. Alternate sides.',
    instructionsEs: 'Paso al lado, toca con el otro pie. Alterna lados.',
  },
  {
    id: 'butt-kicks',
    name: 'Butt Kicks',
    nameEs: 'Talones a Glúteos',
    category: 'cardio',
    muscles: ['hamstrings', 'cardio'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Jog in place kicking heels to glutes.',
    instructionsEs: 'Trota en lugar pateando talones a los glúteos.',
  },
  {
    id: 'speed-skaters',
    name: 'Speed Skaters',
    nameEs: 'Patinadores',
    category: 'cardio',
    muscles: ['legs', 'glutes', 'cardio'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Leap side to side like a speed skater.',
    instructionsEs: 'Salta de lado a lado como patinador.',
  },
  {
    id: 'front-kicks',
    name: 'Front Kicks',
    nameEs: 'Patadas Frontales',
    category: 'cardio',
    muscles: ['legs', 'core', 'cardio'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Alternate kicking legs straight forward.',
    instructionsEs: 'Alterna pateando piernas hacia adelante.',
  },
  {
    id: 'boxer-shuffle',
    name: 'Boxer Shuffle',
    nameEs: 'Shuffle de Boxeador',
    category: 'cardio',
    muscles: ['legs', 'cardio'],
    reps: 40,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Light bounce shifting weight foot to foot like a boxer.',
    instructionsEs: 'Rebote ligero alternando peso de pie a pie como boxeador.',
  },
  {
    id: 'lateral-shuffles',
    name: 'Lateral Shuffles',
    nameEs: 'Desplazamientos Laterales',
    category: 'cardio',
    muscles: ['legs', 'glutes', 'cardio'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Quick shuffle steps side to side.',
    instructionsEs: 'Pasos rápidos de lado a lado.',
  },
  {
    id: 'power-walk',
    name: 'Power Walk in Place',
    nameEs: 'Caminata Potente en Lugar',
    category: 'cardio',
    muscles: ['legs', 'arms', 'cardio'],
    reps: 60,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Walk in place with exaggerated arm swings.',
    instructionsEs: 'Camina en lugar con movimientos exagerados de brazos.',
  },
  {
    id: 'cross-body-punches',
    name: 'Cross Body Punches',
    nameEs: 'Golpes Cruzados',
    category: 'cardio',
    muscles: ['shoulders', 'obliques', 'cardio'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Punch across body with rotation. Fast and powerful.',
    instructionsEs: 'Golpea cruzando el cuerpo con rotación. Rápido y potente.',
  },
  {
    id: 'squat-to-stand',
    name: 'Squat to Stand',
    nameEs: 'Sentadilla y Levantarse',
    category: 'cardio',
    muscles: ['legs', 'glutes', 'cardio'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Squat down, stand up reaching arms overhead. Repeat fast.',
    instructionsEs: 'Baja en sentadilla, levántate estirando brazos. Repite rápido.',
  },
  {
    id: 'standing-side-crunches',
    name: 'Standing Side Crunches',
    nameEs: 'Crunches Laterales de Pie',
    category: 'cardio',
    muscles: ['obliques', 'cardio'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Elbow to knee on same side. Alternate sides quickly.',
    instructionsEs: 'Codo a rodilla del mismo lado. Alterna lados rápido.',
  },
  {
    id: 'star-jumps',
    name: 'Star Jumps',
    nameEs: 'Saltos de Estrella',
    category: 'cardio',
    muscles: ['full-body', 'cardio'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Jump spreading arms and legs into a star shape.',
    instructionsEs: 'Salta abriendo brazos y piernas en forma de estrella.',
  },
];
