// Chair-based exercises for office environments
import { Exercise } from '../exercises';

export const chairExercises: Exercise[] = [
  {
    id: 'chair-jack',
    name: 'Chair Jack',
    nameEs: 'Jack en Silla',
    category: 'chair',
    muscles: ['core', 'legs'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit upright. Spread legs and arms wide, then bring back together.',
    instructionsEs: 'Siéntate erguido. Abre piernas y brazos, luego cierra.',
  },
  {
    id: 'cycling-crunches',
    name: 'Cycling Crunches',
    nameEs: 'Abdominales Bicicleta',
    category: 'chair',
    muscles: ['core', 'obliques'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Lean back slightly. Alternate bringing knee to opposite elbow.',
    instructionsEs: 'Inclínate hacia atrás. Alterna rodilla al codo opuesto.',
  },
  {
    id: 'knee-elbow-twists',
    name: 'Knee-to-Elbow Twists',
    nameEs: 'Giros Rodilla-Codo',
    category: 'chair',
    muscles: ['core', 'obliques'],
    reps: 16,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Twist torso bringing right elbow to left knee, alternate.',
    instructionsEs: 'Gira el torso llevando codo derecho a rodilla izquierda, alterna.',
  },
  {
    id: 'leg-raises-twist',
    name: 'Leg Raises with Twist',
    nameEs: 'Elevaciones con Giro',
    category: 'chair',
    muscles: ['core', 'hip-flexors'],
    reps: 12,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Raise both legs, twist to one side, lower. Repeat other side.',
    instructionsEs: 'Eleva ambas piernas, gira a un lado, baja. Repite al otro lado.',
  },
  {
    id: 'chair-leg-raises',
    name: 'Chair Leg Raises',
    nameEs: 'Elevaciones de Pierna',
    category: 'chair',
    muscles: ['core', 'quads'],
    reps: 15,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit upright. Extend legs straight out, hold, lower slowly.',
    instructionsEs: 'Siéntate erguido. Extiende piernas rectas, mantén, baja lento.',
  },
  {
    id: 'seated-flutter-kicks',
    name: 'Seated Flutter Kicks',
    nameEs: 'Patadas Flutter Sentado',
    category: 'chair',
    muscles: ['core', 'hip-flexors'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Lean back, legs extended. Alternate small up-down kicks.',
    instructionsEs: 'Inclínate atrás, piernas extendidas. Alterna patadas pequeñas.',
  },
  {
    id: 'chair-scissors',
    name: 'Chair Scissors',
    nameEs: 'Tijeras en Silla',
    category: 'chair',
    muscles: ['core', 'inner-thighs'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Legs extended, cross and uncross like scissors.',
    instructionsEs: 'Piernas extendidas, cruza y descruza como tijeras.',
  },
  {
    id: 'seated-knee-tucks',
    name: 'Seated Knee Tucks',
    nameEs: 'Encogidas de Rodilla',
    category: 'chair',
    muscles: ['core', 'hip-flexors'],
    reps: 15,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on chair sides. Pull knees to chest, extend out.',
    instructionsEs: 'Manos a los lados. Lleva rodillas al pecho, extiende.',
  },
  {
    id: 'chair-marches',
    name: 'Chair Marches',
    nameEs: 'Marcha en Silla',
    category: 'chair',
    muscles: ['core', 'hip-flexors'],
    reps: 40,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit tall. March feet up and down rapidly.',
    instructionsEs: 'Siéntate erguido. Marcha rápidamente.',
  },
  {
    id: 'seated-hip-circles',
    name: 'Seated Hip Circles',
    nameEs: 'Círculos de Cadera Sentado',
    category: 'chair',
    muscles: ['core', 'hips'],
    reps: 10,
    sets: 3,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Rotate hips in circles while seated. 5 each direction.',
    instructionsEs: 'Rota las caderas en círculos sentado. 5 cada dirección.',
  },
  {
    id: 'chair-toe-taps',
    name: 'Chair Toe Taps',
    nameEs: 'Toques de Punta Sentado',
    category: 'chair',
    muscles: ['calves', 'shins'],
    reps: 30,
    sets: 3,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Feet flat. Tap toes up rapidly alternating feet.',
    instructionsEs: 'Pies planos. Levanta las puntas rápidamente alternando.',
  },
  {
    id: 'seated-side-bends',
    name: 'Seated Side Bends',
    nameEs: 'Inclinaciones Laterales',
    category: 'chair',
    muscles: ['obliques', 'core'],
    reps: 16,
    sets: 3,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Hands behind head. Lean side to side with control.',
    instructionsEs: 'Manos detrás de la cabeza. Inclínate a los lados con control.',
  },
  {
    id: 'chair-v-ups',
    name: 'Chair V-Ups',
    nameEs: 'V-Ups en Silla',
    category: 'chair',
    muscles: ['core', 'hip-flexors'],
    reps: 12,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Lean back, lift legs and reach toward toes forming a V.',
    instructionsEs: 'Inclínate atrás, eleva piernas y alcanza los pies formando una V.',
  },
  {
    id: 'seated-oblique-punches',
    name: 'Seated Oblique Punches',
    nameEs: 'Golpes Oblicuos Sentado',
    category: 'chair',
    muscles: ['obliques', 'shoulders'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Punch across body with rotation, alternating sides.',
    instructionsEs: 'Golpea cruzando el cuerpo con rotación, alterna lados.',
  },
  {
    id: 'chair-mountain-climbers',
    name: 'Chair Mountain Climbers',
    nameEs: 'Escaladores en Silla',
    category: 'chair',
    muscles: ['core', 'cardio'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Grip seat edges. Alternate driving knees toward chest fast.',
    instructionsEs: 'Agarra los bordes. Alterna llevando rodillas al pecho rápido.',
  },
];
