// Military-style high-intensity exercises for fat burning
import { Exercise } from '../exercises';

export const militaryExercises: Exercise[] = [
  // EXPLOSIVE CARDIO
  {
    id: 'burpees-modified',
    name: 'Modified Burpees',
    nameEs: 'Burpees Modificados',
    category: 'cardio',
    muscles: ['full-body', 'cardio'],
    reps: 10,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Squat, hands down, step or jump back to plank, return, stand. Repeat fast.',
    instructionsEs: 'Sentadilla, manos abajo, paso o salto a plancha, regresa, levántate. Rápido.',
  },
  {
    id: 'military-pushups',
    name: 'Military Push-ups',
    nameEs: 'Lagartijas Militares',
    category: 'strength',
    muscles: ['chest', 'triceps', 'core'],
    reps: 20,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Strict form push-ups. Chest to floor, full extension. No rest at top.',
    instructionsEs: 'Lagartijas estrictas. Pecho al piso, extensión completa. Sin pausar arriba.',
  },
  {
    id: 'mountain-climbers-fast',
    name: 'Fast Mountain Climbers',
    nameEs: 'Escaladores Rápidos',
    category: 'cardio',
    muscles: ['core', 'cardio', 'shoulders'],
    reps: 40,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Plank position. Drive knees to chest as fast as possible.',
    instructionsEs: 'Posición de plancha. Lleva rodillas al pecho lo más rápido posible.',
  },
  {
    id: 'squat-jumps',
    name: 'Squat Jumps',
    nameEs: 'Sentadillas con Salto',
    category: 'cardio',
    muscles: ['quads', 'glutes', 'cardio'],
    reps: 15,
    sets: 4,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Deep squat, explode up into jump, soft landing. Repeat immediately.',
    instructionsEs: 'Sentadilla profunda, explota en salto, aterriza suave. Repite inmediato.',
  },
  {
    id: 'flutter-kicks-military',
    name: 'Military Flutter Kicks',
    nameEs: 'Patadas Flutter Militar',
    category: 'strength',
    muscles: ['core', 'hip-flexors'],
    reps: 40,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Lie back, hands under glutes, legs 6 inches off floor. Rapid kicks.',
    instructionsEs: 'Acostado, manos bajo glúteos, piernas 15 cm del piso. Patadas rápidas.',
  },
  {
    id: 'plank-jacks',
    name: 'Plank Jacks',
    nameEs: 'Jacks en Plancha',
    category: 'cardio',
    muscles: ['core', 'shoulders', 'cardio'],
    reps: 20,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'In plank, jump feet out and in like jumping jacks.',
    instructionsEs: 'En plancha, salta pies afuera y adentro como jumping jacks.',
  },
  {
    id: 'tuck-jumps',
    name: 'Tuck Jumps',
    nameEs: 'Saltos con Rodillas Arriba',
    category: 'cardio',
    muscles: ['quads', 'core', 'cardio'],
    reps: 10,
    sets: 4,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Jump high, bring knees to chest in air. Soft landing.',
    instructionsEs: 'Salta alto, lleva rodillas al pecho en el aire. Aterriza suave.',
  },
  {
    id: 'diamond-pushups',
    name: 'Diamond Push-ups',
    nameEs: 'Lagartijas Diamante',
    category: 'strength',
    muscles: ['triceps', 'chest'],
    reps: 12,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Hands form diamond under chest. Lower and push up.',
    instructionsEs: 'Manos forman diamante bajo el pecho. Baja y empuja.',
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists',
    nameEs: 'Giros Rusos',
    category: 'strength',
    muscles: ['obliques', 'core'],
    reps: 30,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Sit, lean back, feet up. Rotate touching floor each side.',
    instructionsEs: 'Siéntate, inclínate, pies arriba. Rota tocando el piso cada lado.',
  },
  {
    id: 'power-lunges',
    name: 'Power Lunges',
    nameEs: 'Zancadas Potentes',
    category: 'cardio',
    muscles: ['quads', 'glutes', 'cardio'],
    reps: 20,
    sets: 4,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Jump switching legs in lunge position. Fast and explosive.',
    instructionsEs: 'Salta alternando piernas en zancada. Rápido y explosivo.',
  },
  {
    id: 'commandos',
    name: 'Commandos',
    nameEs: 'Comandos',
    category: 'strength',
    muscles: ['core', 'shoulders', 'triceps'],
    reps: 16,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Plank to push-up position and back. One arm at a time.',
    instructionsEs: 'De plancha a lagartija y regresa. Un brazo a la vez.',
  },
  {
    id: 'bicycle-crunches-fast',
    name: 'Fast Bicycle Crunches',
    nameEs: 'Bicicleta Rápida',
    category: 'strength',
    muscles: ['core', 'obliques'],
    reps: 40,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Lie back. Alternate elbow to opposite knee fast.',
    instructionsEs: 'Acostado. Alterna codo a rodilla opuesta rápido.',
  },
  {
    id: 'sprawls',
    name: 'Sprawls',
    nameEs: 'Sprawls',
    category: 'cardio',
    muscles: ['full-body', 'cardio'],
    reps: 12,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Like burpee without jump. Drop to plank, hips to floor, return.',
    instructionsEs: 'Como burpee sin salto. Baja a plancha, caderas al piso, regresa.',
  },
  {
    id: 'v-ups',
    name: 'V-Ups',
    nameEs: 'V-Ups',
    category: 'strength',
    muscles: ['core'],
    reps: 15,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 3,
    instructions: 'Lie flat. Lift legs and torso to touch toes. Lower with control.',
    instructionsEs: 'Acostado. Levanta piernas y torso para tocar puntas. Baja con control.',
  },
  {
    id: 'bear-crawls',
    name: 'Bear Crawls',
    nameEs: 'Gateo de Oso',
    category: 'cardio',
    muscles: ['full-body', 'cardio'],
    reps: 20,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands and feet on floor, knees off. Crawl forward/backward.',
    instructionsEs: 'Manos y pies en el piso, rodillas arriba. Gatea adelante/atrás.',
  },
  {
    id: 'side-plank-dips',
    name: 'Side Plank Dips',
    nameEs: 'Fondos en Plancha Lateral',
    category: 'strength',
    muscles: ['obliques', 'shoulders'],
    reps: 12,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Side plank. Dip hip to floor, lift back up. Switch sides.',
    instructionsEs: 'Plancha lateral. Baja cadera al piso, sube. Cambia lados.',
  },
  {
    id: 'inchworms',
    name: 'Inchworms',
    nameEs: 'Gusano',
    category: 'cardio',
    muscles: ['full-body', 'core'],
    reps: 10,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Bend forward, walk hands to plank, walk feet to hands, stand.',
    instructionsEs: 'Inclínate, camina manos a plancha, camina pies a manos, levántate.',
  },
  {
    id: 'plank-hold',
    name: 'Plank Hold',
    nameEs: 'Plancha Sostenida',
    category: 'strength',
    muscles: ['core', 'shoulders'],
    reps: 1,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hold plank position for 45-60 seconds. Keep body straight.',
    instructionsEs: 'Mantén plancha 45-60 segundos. Mantén cuerpo recto.',
  },
  {
    id: 'ski-jumps',
    name: 'Ski Jumps',
    nameEs: 'Saltos de Esquí',
    category: 'cardio',
    muscles: ['legs', 'cardio'],
    reps: 20,
    sets: 4,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: true,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Jump side to side, feet together, like a skier.',
    instructionsEs: 'Salta de lado a lado, pies juntos, como esquiador.',
  },
  {
    id: 'superman-holds',
    name: 'Superman Holds',
    nameEs: 'Superman Sostenido',
    category: 'strength',
    muscles: ['lower-back', 'glutes'],
    reps: 10,
    sets: 4,
    restSeconds: 30,
    requiresFloor: true,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Lie face down. Lift arms and legs. Hold 5 sec each rep.',
    instructionsEs: 'Boca abajo. Levanta brazos y piernas. Mantén 5 seg cada rep.',
  },
];
