// Office-specific exercises
import { Exercise } from '../exercises';

export const officeExercises: Exercise[] = [
  {
    id: 'desk-plank',
    name: 'Desk Plank',
    nameEs: 'Plancha de Escritorio',
    category: 'office',
    muscles: ['core', 'shoulders'],
    reps: 1,
    sets: 3,
    restSeconds: 60,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on desk edge. Hold plank position for 30-60 seconds.',
    instructionsEs: 'Manos en el borde del escritorio. Mantén plancha 30-60 seg.',
  },
  {
    id: 'seated-boxer',
    name: 'Seated Boxer',
    nameEs: 'Boxeador Sentado',
    category: 'office',
    muscles: ['shoulders', 'core'],
    reps: 30,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit tall. Throw alternating punches with rotation.',
    instructionsEs: 'Siéntate erguido. Lanza golpes alternados con rotación.',
  },
  {
    id: 'arm-circles',
    name: 'Arm Circles',
    nameEs: 'Círculos de Brazos',
    category: 'office',
    muscles: ['shoulders'],
    reps: 20,
    sets: 3,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Arms extended. Make small circles forward, then backward.',
    instructionsEs: 'Brazos extendidos. Haz círculos pequeños adelante, luego atrás.',
  },
  {
    id: 'standing-desk-crunches',
    name: 'Standing Desk Crunches',
    nameEs: 'Abdominales en Escritorio',
    category: 'office',
    muscles: ['core'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Hold desk. Bring knee to chest alternating.',
    instructionsEs: 'Agarra el escritorio. Lleva rodilla al pecho alternando.',
  },
  {
    id: 'desk-shoulder-shrugs',
    name: 'Desk Shoulder Shrugs',
    nameEs: 'Encogimiento de Hombros',
    category: 'office',
    muscles: ['shoulders', 'traps'],
    reps: 15,
    sets: 3,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Shrug shoulders up to ears, hold 2 sec, release.',
    instructionsEs: 'Sube hombros a las orejas, mantén 2 seg, suelta.',
  },
  {
    id: 'typing-breaks',
    name: 'Typing Finger Stretches',
    nameEs: 'Estiramientos de Dedos',
    category: 'office',
    muscles: ['fingers', 'hands'],
    reps: 10,
    sets: 3,
    restSeconds: 15,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Spread fingers wide, make fists, repeat. Shake out hands.',
    instructionsEs: 'Abre los dedos, haz puños, repite. Sacude las manos.',
  },
  {
    id: 'desk-leg-extensions',
    name: 'Desk Leg Extensions',
    nameEs: 'Extensiones de Pierna',
    category: 'office',
    muscles: ['quads'],
    reps: 15,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Seated, extend one leg straight, hold 3 sec. Alternate.',
    instructionsEs: 'Sentado, extiende una pierna recta, mantén 3 seg. Alterna.',
  },
  {
    id: 'standing-calf-pumps',
    name: 'Standing Calf Pumps',
    nameEs: 'Bombeo de Pantorrillas',
    category: 'office',
    muscles: ['calves'],
    reps: 25,
    sets: 3,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Hold desk for balance. Rise onto toes rapidly.',
    instructionsEs: 'Agárrate del escritorio. Sube a las puntas rápidamente.',
  },
  {
    id: 'desk-tricep-pushes',
    name: 'Desk Tricep Pushes',
    nameEs: 'Empujes de Tríceps',
    category: 'office',
    muscles: ['triceps'],
    reps: 12,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on desk behind you. Push body away using triceps.',
    instructionsEs: 'Manos en escritorio detrás. Empuja el cuerpo usando tríceps.',
  },
  {
    id: 'chair-hip-rotations',
    name: 'Chair Hip Rotations',
    nameEs: 'Rotaciones de Cadera',
    category: 'office',
    muscles: ['hips', 'core'],
    reps: 10,
    sets: 3,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Seated, rotate hips in circles. 5 each direction.',
    instructionsEs: 'Sentado, rota las caderas en círculos. 5 cada dirección.',
  },
  {
    id: 'standing-knee-raises',
    name: 'Standing Knee Raises',
    nameEs: 'Elevaciones de Rodilla de Pie',
    category: 'office',
    muscles: ['core', 'hip-flexors'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Stand tall. Raise one knee to hip height, alternate.',
    instructionsEs: 'De pie erguido. Eleva una rodilla a altura de cadera, alterna.',
  },
  {
    id: 'desk-mountain-climbers',
    name: 'Desk Mountain Climbers',
    nameEs: 'Escaladores de Escritorio',
    category: 'office',
    muscles: ['core', 'cardio'],
    reps: 20,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on desk, body angled. Drive knees to chest fast.',
    instructionsEs: 'Manos en escritorio, cuerpo inclinado. Lleva rodillas al pecho rápido.',
  },
  {
    id: 'chair-back-extensions',
    name: 'Chair Back Extensions',
    nameEs: 'Extensiones de Espalda',
    category: 'office',
    muscles: ['lower-back'],
    reps: 12,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit edge of chair. Round back, then extend and arch slightly.',
    instructionsEs: 'Siéntate al borde. Redondea espalda, luego extiende y arquea.',
  },
  {
    id: 'standing-chest-squeeze',
    name: 'Standing Chest Squeeze',
    nameEs: 'Apriete de Pecho',
    category: 'office',
    muscles: ['chest'],
    reps: 15,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Palms together at chest. Press hard together for 5 seconds.',
    instructionsEs: 'Palmas juntas en el pecho. Presiona fuerte 5 segundos.',
  },
  {
    id: 'desk-tap-dance',
    name: 'Desk Tap Dance',
    nameEs: 'Tap Dance en Escritorio',
    category: 'office',
    muscles: ['calves', 'cardio'],
    reps: 40,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Quickly tap toes alternating under desk.',
    instructionsEs: 'Golpea rápido con las puntas alternando bajo el escritorio.',
  },
];
