// Strength exercises for office environments
import { Exercise } from '../exercises';

export const strengthExercises: Exercise[] = [
  {
    id: 'tricep-dips-chair',
    name: 'Tricep Dips',
    nameEs: 'Fondos de Tríceps',
    category: 'strength',
    muscles: ['triceps', 'shoulders'],
    reps: 12,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on chair edge. Lower body by bending elbows, push back up.',
    instructionsEs: 'Manos en el borde. Baja doblando codos, empuja hacia arriba.',
  },
  {
    id: 'wall-pushups',
    name: 'Wall Push-ups',
    nameEs: 'Lagartijas de Pared',
    category: 'strength',
    muscles: ['chest', 'triceps', 'shoulders'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Face wall, arms extended. Lower chest to wall, push back.',
    instructionsEs: 'Frente a la pared, brazos extendidos. Baja el pecho, empuja.',
  },
  {
    id: 'chair-squats',
    name: 'Chair Squats',
    nameEs: 'Sentadillas con Silla',
    category: 'strength',
    muscles: ['quads', 'glutes'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Stand in front of chair. Squat until touching seat, stand up.',
    instructionsEs: 'De pie frente a la silla. Baja hasta tocar, levántate.',
  },
  {
    id: 'calf-raises',
    name: 'Calf Raises',
    nameEs: 'Elevaciones de Pantorrilla',
    category: 'strength',
    muscles: ['calves'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Stand tall. Rise onto toes, hold, lower slowly.',
    instructionsEs: 'De pie erguido. Sube a las puntas, mantén, baja lento.',
  },
  {
    id: 'wide-squats',
    name: 'Wide Squats',
    nameEs: 'Sentadilla Sumo',
    category: 'strength',
    muscles: ['quads', 'glutes', 'inner-thighs'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Wide stance, toes out. Squat deep, keep back straight.',
    instructionsEs: 'Postura amplia, puntas afuera. Baja profundo, espalda recta.',
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    nameEs: 'Sentadilla en Pared',
    category: 'strength',
    muscles: ['quads', 'glutes'],
    reps: 1,
    sets: 3,
    restSeconds: 60,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Back against wall, slide down to 90 degrees. Hold 30-60 seconds.',
    instructionsEs: 'Espalda contra la pared, baja a 90 grados. Mantén 30-60 seg.',
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single Leg Calf Raise',
    nameEs: 'Elevación de Pantorrilla Una Pierna',
    category: 'strength',
    muscles: ['calves'],
    reps: 12,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Stand on one leg. Rise onto toes, lower with control. Switch.',
    instructionsEs: 'De pie en una pierna. Sube a la punta, baja con control. Cambia.',
  },
  {
    id: 'incline-pushups',
    name: 'Incline Push-ups',
    nameEs: 'Lagartijas Inclinadas',
    category: 'strength',
    muscles: ['chest', 'triceps'],
    reps: 12,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on desk or chair. Lower chest, push back up.',
    instructionsEs: 'Manos en escritorio o silla. Baja el pecho, empuja.',
  },
  {
    id: 'split-squats',
    name: 'Split Squats',
    nameEs: 'Sentadilla Dividida',
    category: 'strength',
    muscles: ['quads', 'glutes'],
    reps: 10,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'One foot forward. Lower back knee toward floor, push up.',
    instructionsEs: 'Un pie adelante. Baja la rodilla trasera hacia el piso, sube.',
  },
  {
    id: 'glute-bridges-standing',
    name: 'Standing Glute Squeeze',
    nameEs: 'Apriete de Glúteos de Pie',
    category: 'strength',
    muscles: ['glutes'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Stand tall. Squeeze glutes hard, hold 2 seconds, release.',
    instructionsEs: 'De pie. Aprieta glúteos fuerte, mantén 2 seg, suelta.',
  },
  {
    id: 'desk-pushups',
    name: 'Desk Push-ups',
    nameEs: 'Lagartijas de Escritorio',
    category: 'strength',
    muscles: ['chest', 'triceps', 'core'],
    reps: 15,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Hands on desk edge, body straight. Lower and push.',
    instructionsEs: 'Manos en el borde del escritorio, cuerpo recto. Baja y empuja.',
  },
  {
    id: 'isometric-squat-hold',
    name: 'Isometric Squat Hold',
    nameEs: 'Sentadilla Isométrica',
    category: 'strength',
    muscles: ['quads', 'glutes'],
    reps: 1,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Squat to 90 degrees. Hold position for 30-45 seconds.',
    instructionsEs: 'Sentadilla a 90 grados. Mantén la posición 30-45 seg.',
  },
  {
    id: 'reverse-lunges',
    name: 'Reverse Lunges',
    nameEs: 'Zancadas Inversas',
    category: 'strength',
    muscles: ['quads', 'glutes', 'hamstrings'],
    reps: 12,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Step back into lunge, knee toward floor. Return. Alternate.',
    instructionsEs: 'Paso atrás en zancada, rodilla al piso. Regresa. Alterna.',
  },
  {
    id: 'heel-raises-wall',
    name: 'Wall Heel Raises',
    nameEs: 'Elevaciones de Talón en Pared',
    category: 'strength',
    muscles: ['calves', 'shins'],
    reps: 20,
    sets: 3,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Lean against wall. Raise heels, then raise toes. Alternate.',
    instructionsEs: 'Apóyate en la pared. Sube talones, luego puntas. Alterna.',
  },
  {
    id: 'sumo-pulse-squats',
    name: 'Sumo Pulse Squats',
    nameEs: 'Pulsos Sentadilla Sumo',
    category: 'strength',
    muscles: ['quads', 'glutes', 'inner-thighs'],
    reps: 20,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Wide stance. Stay low and pulse up and down 2 inches.',
    instructionsEs: 'Postura amplia. Mantente abajo y pulsa arriba y abajo 5 cm.',
  },
];
