// Stretch exercises for office environments
import { Exercise } from '../exercises';

export const stretchExercises: Exercise[] = [
  {
    id: 'neck-rolls',
    name: 'Neck Rolls',
    nameEs: 'Giros de Cuello',
    category: 'stretch',
    muscles: ['neck'],
    reps: 10,
    sets: 2,
    restSeconds: 15,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Slowly roll head in circles. 5 each direction.',
    instructionsEs: 'Gira la cabeza lentamente en círculos. 5 cada dirección.',
  },
  {
    id: 'shoulder-stretch',
    name: 'Shoulder Stretch',
    nameEs: 'Estiramiento de Hombro',
    category: 'stretch',
    muscles: ['shoulders'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Cross arm over chest. Hold 20-30 seconds each side.',
    instructionsEs: 'Cruza el brazo sobre el pecho. Mantén 20-30 seg cada lado.',
  },
  {
    id: 'wrist-stretch',
    name: 'Wrist Stretch',
    nameEs: 'Estiramiento de Muñeca',
    category: 'stretch',
    muscles: ['wrists', 'forearms'],
    reps: 1,
    sets: 3,
    restSeconds: 15,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Extend arm, pull fingers back gently. Hold 15 sec each.',
    instructionsEs: 'Extiende el brazo, jala los dedos suavemente. 15 seg cada uno.',
  },
  {
    id: 'seated-twist',
    name: 'Seated Twist',
    nameEs: 'Giro Sentado',
    category: 'stretch',
    muscles: ['back', 'obliques'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Sit tall. Twist to one side, hold. Repeat other side.',
    instructionsEs: 'Siéntate erguido. Gira a un lado, mantén. Repite al otro.',
  },
  {
    id: 'standing-quad-stretch',
    name: 'Standing Quad Stretch',
    nameEs: 'Estiramiento de Cuádriceps',
    category: 'stretch',
    muscles: ['quads'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Pull heel to glute. Hold 20-30 sec each leg.',
    instructionsEs: 'Jala el talón al glúteo. Mantén 20-30 seg cada pierna.',
  },
  {
    id: 'seated-hamstring-stretch',
    name: 'Seated Hamstring Stretch',
    nameEs: 'Estiramiento de Isquiotibiales',
    category: 'stretch',
    muscles: ['hamstrings'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Extend one leg. Reach for toes. Hold 20-30 sec each.',
    instructionsEs: 'Extiende una pierna. Alcanza los dedos. 20-30 seg cada una.',
  },
  {
    id: 'chest-doorway-stretch',
    name: 'Doorway Chest Stretch',
    nameEs: 'Estiramiento de Pecho en Puerta',
    category: 'stretch',
    muscles: ['chest', 'shoulders'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Arm on doorframe, lean through. Hold 20-30 sec each.',
    instructionsEs: 'Brazo en el marco, inclínate. Mantén 20-30 seg cada lado.',
  },
  {
    id: 'tricep-overhead-stretch',
    name: 'Tricep Overhead Stretch',
    nameEs: 'Estiramiento de Tríceps',
    category: 'stretch',
    muscles: ['triceps'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Reach behind head, pull elbow. Hold 15-20 sec each.',
    instructionsEs: 'Alcanza detrás de la cabeza, jala el codo. 15-20 seg cada uno.',
  },
  {
    id: 'standing-side-stretch',
    name: 'Standing Side Stretch',
    nameEs: 'Estiramiento Lateral de Pie',
    category: 'stretch',
    muscles: ['obliques', 'lats'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Reach arm overhead, lean to opposite side. Hold 15 sec.',
    instructionsEs: 'Estira brazo arriba, inclínate al lado opuesto. 15 seg.',
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Standing Hip Flexor Stretch',
    nameEs: 'Estiramiento de Flexor de Cadera',
    category: 'stretch',
    muscles: ['hip-flexors'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Lunge stance, push hips forward. Hold 20-30 sec each.',
    instructionsEs: 'Postura de zancada, empuja caderas adelante. 20-30 seg cada lado.',
  },
  {
    id: 'upper-back-stretch',
    name: 'Upper Back Stretch',
    nameEs: 'Estiramiento de Espalda Alta',
    category: 'stretch',
    muscles: ['upper-back', 'rhomboids'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Clasp hands forward, round upper back, push away.',
    instructionsEs: 'Entrelaza manos adelante, redondea espalda, empuja.',
  },
  {
    id: 'ankle-circles',
    name: 'Ankle Circles',
    nameEs: 'Círculos de Tobillo',
    category: 'stretch',
    muscles: ['ankles'],
    reps: 10,
    sets: 2,
    restSeconds: 15,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Lift foot, rotate ankle in circles. 5 each direction per foot.',
    instructionsEs: 'Levanta el pie, rota el tobillo. 5 cada dirección por pie.',
  },
  {
    id: 'forearm-stretch',
    name: 'Forearm Stretch',
    nameEs: 'Estiramiento de Antebrazo',
    category: 'stretch',
    muscles: ['forearms'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Extend arm, pull fingers down, then up. Hold 10 sec each.',
    instructionsEs: 'Extiende el brazo, jala dedos abajo, luego arriba. 10 seg cada uno.',
  },
  {
    id: 'figure-four-seated',
    name: 'Seated Figure Four',
    nameEs: 'Cuatro Sentado',
    category: 'stretch',
    muscles: ['glutes', 'hips'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Cross ankle over knee. Lean forward gently. Hold 20-30 sec.',
    instructionsEs: 'Cruza tobillo sobre rodilla. Inclínate adelante. 20-30 seg.',
  },
  {
    id: 'chin-tucks',
    name: 'Chin Tucks',
    nameEs: 'Retracción de Mentón',
    category: 'stretch',
    muscles: ['neck'],
    reps: 10,
    sets: 2,
    restSeconds: 15,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Pull chin back creating double chin. Hold 5 sec, release.',
    instructionsEs: 'Jala el mentón hacia atrás. Mantén 5 seg, suelta.',
  },
];
