// Yoga exercises for office environments
import { Exercise } from '../exercises';

export const yogaExercises: Exercise[] = [
  {
    id: 'chair-tree-pose',
    name: 'Chair Tree Pose',
    nameEs: 'Postura del Árbol',
    category: 'yoga',
    muscles: ['balance', 'legs', 'core'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Stand on one leg, foot on ankle or calf. Arms up. Hold 30 sec.',
    instructionsEs: 'De pie en una pierna, pie en tobillo o pantorrilla. Brazos arriba. 30 seg.',
  },
  {
    id: 'chair-warrior',
    name: 'Chair Warrior I',
    nameEs: 'Guerrero I en Silla',
    category: 'yoga',
    muscles: ['legs', 'hips', 'shoulders'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'One leg forward, back leg extended. Arms overhead. Hold 30 sec.',
    instructionsEs: 'Una pierna adelante, la otra atrás. Brazos arriba. Mantén 30 seg.',
  },
  {
    id: 'cat-cow-seated',
    name: 'Seated Cat-Cow',
    nameEs: 'Gato-Vaca Sentado',
    category: 'yoga',
    muscles: ['spine', 'core'],
    reps: 10,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Arch back looking up (cow), round back chin to chest (cat).',
    instructionsEs: 'Arquea la espalda mirando arriba (vaca), redondea barbilla al pecho (gato).',
  },
  {
    id: 'standing-forward-fold',
    name: 'Standing Forward Fold',
    nameEs: 'Flexión Hacia Adelante',
    category: 'yoga',
    muscles: ['hamstrings', 'back'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Fold forward from hips, let arms hang. Hold 30 sec.',
    instructionsEs: 'Flexiona desde las caderas, deja colgar los brazos. 30 seg.',
  },
  {
    id: 'warrior-two',
    name: 'Warrior II',
    nameEs: 'Guerrero II',
    category: 'yoga',
    muscles: ['legs', 'hips', 'arms'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Wide stance, front knee bent. Arms extended. Hold 30 sec each.',
    instructionsEs: 'Postura amplia, rodilla frontal doblada. Brazos extendidos. 30 seg.',
  },
  {
    id: 'chair-pose',
    name: 'Chair Pose (Utkatasana)',
    nameEs: 'Postura de la Silla',
    category: 'yoga',
    muscles: ['quads', 'glutes', 'core'],
    reps: 1,
    sets: 3,
    restSeconds: 45,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Squat as if sitting in invisible chair. Arms up. Hold 30 sec.',
    instructionsEs: 'Sentadilla como si te sentaras. Brazos arriba. 30 seg.',
  },
  {
    id: 'standing-crescent',
    name: 'Standing Crescent Moon',
    nameEs: 'Luna Creciente de Pie',
    category: 'yoga',
    muscles: ['obliques', 'back'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Arms overhead, lean to one side. Hold 15-20 sec each.',
    instructionsEs: 'Brazos arriba, inclínate a un lado. 15-20 seg cada lado.',
  },
  {
    id: 'eagle-arms',
    name: 'Eagle Arms',
    nameEs: 'Brazos de Águila',
    category: 'yoga',
    muscles: ['shoulders', 'upper-back'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 2,
    instructions: 'Wrap arms, lift elbows. Hold 20 sec, switch sides.',
    instructionsEs: 'Envuelve los brazos, levanta codos. 20 seg, cambia lados.',
  },
  {
    id: 'seated-pigeon',
    name: 'Seated Pigeon',
    nameEs: 'Paloma Sentada',
    category: 'yoga',
    muscles: ['hips', 'glutes'],
    reps: 1,
    sets: 2,
    restSeconds: 30,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Cross ankle over knee. Press knee gently. Hold 30 sec each.',
    instructionsEs: 'Cruza tobillo sobre rodilla. Presiona suavemente. 30 seg cada lado.',
  },
  {
    id: 'mountain-pose',
    name: 'Mountain Pose',
    nameEs: 'Postura de la Montaña',
    category: 'yoga',
    muscles: ['full-body', 'balance'],
    reps: 1,
    sets: 2,
    restSeconds: 20,
    requiresFloor: false,
    requiresJumps: false,
    requiresEquipment: false,
    difficulty: 1,
    instructions: 'Stand tall, feet together, arms at sides. Focus on posture. 30 sec.',
    instructionsEs: 'De pie, pies juntos, brazos a los lados. Enfócate en postura. 30 seg.',
  },
];
